/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */
import type {
    HttpResponse as AngularHttpResponse,
    HttpContext,
    HttpEvent,
    HttpHeaders,
    HttpParams,
} from '@angular/common/http';
import { HttpClient } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { GetLoginUserResponse, LogoutRequest } from '.././model';

interface HttpClientOptions {
    headers?: HttpHeaders | Record<string, string | string[]>;
    context?: HttpContext;
    params?: HttpParams | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
    reportProgress?: boolean;
    withCredentials?: boolean;
    credentials?: RequestCredentials;
    keepalive?: boolean;
    priority?: RequestPriority;
    cache?: RequestCache;
    mode?: RequestMode;
    redirect?: RequestRedirect;
    referrer?: string;
    integrity?: string;
    transferCache?: { includeHeaders?: string[] } | boolean;
    timeout?: number;
}

@Injectable({ providedIn: 'root' })
export class CommonService {
    private readonly http = inject(HttpClient);
    /**
     * ユーザーのログアウト処理を実行し、関連するリフレッシュトークンを無効化します。
     * @summary ログアウトAPI
     */
    logout<TData = void>(
        logoutRequest: LogoutRequest,
        options?: HttpClientOptions & { observe?: 'body' },
    ): Observable<TData>;
    logout<TData = void>(
        logoutRequest: LogoutRequest,
        options?: HttpClientOptions & { observe: 'events' },
    ): Observable<HttpEvent<TData>>;
    logout<TData = void>(
        logoutRequest: LogoutRequest,
        options?: HttpClientOptions & { observe: 'response' },
    ): Observable<AngularHttpResponse<TData>>;
    logout<TData = void>(
        logoutRequest: LogoutRequest,
        options?: HttpClientOptions & { observe?: any },
    ): Observable<any> {
        return this.http.post<TData>(`http://localhost:56080/api/common/logout`, logoutRequest, options);
    }
    /**
     * 現在ログインしているユーザーの情報を取得します。
     * @summary ログインユーザー情報取得API
     */
    getLoginUser<TData = GetLoginUserResponse>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
    getLoginUser<TData = GetLoginUserResponse>(
        options?: HttpClientOptions & { observe: 'events' },
    ): Observable<HttpEvent<TData>>;
    getLoginUser<TData = GetLoginUserResponse>(
        options?: HttpClientOptions & { observe: 'response' },
    ): Observable<AngularHttpResponse<TData>>;
    getLoginUser<TData = GetLoginUserResponse>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
        return this.http.get<TData>(`http://localhost:56080/api/common/loginUser`, options);
    }
}

export type LogoutClientResult = NonNullable<void>;
export type GetLoginUserClientResult = NonNullable<GetLoginUserResponse>;
