/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */
import type {
    AuthTokenResponse,
    GetLoginUserResponse,
    LoginRequest,
    LogoutRequest,
    RefreshRequest,
    UsersResponse,
} from './model';

/**
 * ユーザーのログイン認証を行い、認証トークンを返却します。
 * @summary ログインAPI
 */
export const getLoginUrl = () => {
    return `http://localhost:56080/api/login`;
};

export const login = async (loginRequest: LoginRequest, options?: RequestInit): Promise<AuthTokenResponse> => {
    const res = await fetch(getLoginUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(loginRequest),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: AuthTokenResponse = body ? JSON.parse(body) : {};
    return data;
};

/**
 * リフレッシュトークンを使用して、新しい認証トークンを取得します。
 * @summary トークンリフレッシュAPI
 */
export const getRefreshAuthTokenUrl = () => {
    return `http://localhost:56080/api/login/refresh`;
};

export const refreshAuthToken = async (
    refreshRequest: RefreshRequest,
    options?: RequestInit,
): Promise<AuthTokenResponse> => {
    const res = await fetch(getRefreshAuthTokenUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(refreshRequest),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: AuthTokenResponse = body ? JSON.parse(body) : {};
    return data;
};

/**
 * ユーザーのログアウト処理を実行し、関連するリフレッシュトークンを無効化します。
 * @summary ログアウトAPI
 */
export const getLogoutUrl = () => {
    return `http://localhost:56080/api/common/logout`;
};

export const logout = async (logoutRequest: LogoutRequest, options?: RequestInit): Promise<void> => {
    const res = await fetch(getLogoutUrl(), {
        ...options,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...options?.headers },
        body: JSON.stringify(logoutRequest),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: void = body ? JSON.parse(body) : {};
    return data;
};

/**
 * 登録されているすべてのユーザー情報を取得します。
 * @summary ユーザー一覧取得API
 */
export const getGetMastersUsersUrl = () => {
    return `http://localhost:56080/api/masters/users`;
};

export const getMastersUsers = async (options?: RequestInit): Promise<UsersResponse> => {
    const res = await fetch(getGetMastersUsersUrl(), {
        ...options,
        method: 'GET',
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: UsersResponse = body ? JSON.parse(body) : {};
    return data;
};

/**
 * 現在ログインしているユーザーの情報を取得します。
 * @summary ログインユーザー情報取得API
 */
export const getGetLoginUserUrl = () => {
    return `http://localhost:56080/api/common/loginUser`;
};

export const getLoginUser = async (options?: RequestInit): Promise<GetLoginUserResponse> => {
    const res = await fetch(getGetLoginUserUrl(), {
        ...options,
        method: 'GET',
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: GetLoginUserResponse = body ? JSON.parse(body) : {};
    return data;
};
