/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */
import type {
    HttpResponse as AngularHttpResponse,
    HttpContext,
    HttpEvent,
    HttpHeaders,
    HttpParams,
} from '@angular/common/http';
import { HttpClient } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { AuthTokenResponse, LoginRequest, RefreshRequest } from '.././model';

interface HttpClientOptions {
    headers?: HttpHeaders | Record<string, string | string[]>;
    context?: HttpContext;
    params?: HttpParams | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
    reportProgress?: boolean;
    withCredentials?: boolean;
    credentials?: RequestCredentials;
    keepalive?: boolean;
    priority?: RequestPriority;
    cache?: RequestCache;
    mode?: RequestMode;
    redirect?: RequestRedirect;
    referrer?: string;
    integrity?: string;
    transferCache?: { includeHeaders?: string[] } | boolean;
    timeout?: number;
}

@Injectable({ providedIn: 'root' })
export class LoginService {
    private readonly http = inject(HttpClient);
    /**
     * ユーザーのログイン認証を行い、認証トークンを返却します。
     * @summary ログインAPI
     */
    login<TData = AuthTokenResponse>(
        loginRequest: LoginRequest,
        options?: HttpClientOptions & { observe?: 'body' },
    ): Observable<TData>;
    login<TData = AuthTokenResponse>(
        loginRequest: LoginRequest,
        options?: HttpClientOptions & { observe: 'events' },
    ): Observable<HttpEvent<TData>>;
    login<TData = AuthTokenResponse>(
        loginRequest: LoginRequest,
        options?: HttpClientOptions & { observe: 'response' },
    ): Observable<AngularHttpResponse<TData>>;
    login<TData = AuthTokenResponse>(
        loginRequest: LoginRequest,
        options?: HttpClientOptions & { observe?: any },
    ): Observable<any> {
        return this.http.post<TData>(`http://localhost:56080/api/login`, loginRequest, options);
    }
    /**
     * リフレッシュトークンを使用して、新しい認証トークンを取得します。
     * @summary トークンリフレッシュAPI
     */
    refreshAuthToken<TData = AuthTokenResponse>(
        refreshRequest: RefreshRequest,
        options?: HttpClientOptions & { observe?: 'body' },
    ): Observable<TData>;
    refreshAuthToken<TData = AuthTokenResponse>(
        refreshRequest: RefreshRequest,
        options?: HttpClientOptions & { observe: 'events' },
    ): Observable<HttpEvent<TData>>;
    refreshAuthToken<TData = AuthTokenResponse>(
        refreshRequest: RefreshRequest,
        options?: HttpClientOptions & { observe: 'response' },
    ): Observable<AngularHttpResponse<TData>>;
    refreshAuthToken<TData = AuthTokenResponse>(
        refreshRequest: RefreshRequest,
        options?: HttpClientOptions & { observe?: any },
    ): Observable<any> {
        return this.http.post<TData>(`http://localhost:56080/api/login/refresh`, refreshRequest, options);
    }
}

export type LoginClientResult = NonNullable<AuthTokenResponse>;
export type RefreshAuthTokenClientResult = NonNullable<AuthTokenResponse>;
