/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */
import type { GetLoginUserResponseRole } from './get-login-user-response-role';

/**
 * ログインユーザー情報取得APIのレスポンス
 */
export interface GetLoginUserResponse {
    /** アカウント名 */
    account?: string;
    /** ユーザー名 */
    name?: string;
    /** 役割 */
    role?: GetLoginUserResponseRole;
}
