/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */

/**
 * 役割
 */
export type GetLoginUserResponseRole = (typeof GetLoginUserResponseRole)[keyof typeof GetLoginUserResponseRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetLoginUserResponseRole = {
    Admin: 'Admin',
    Common: 'Common',
} as const;
