/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */

/**
 * トークンリフレッシュAPIのリクエストボディ
 */
export interface RefreshRequest {
    /**
     * リフレッシュトークン
     * @minLength 1
     */
    refreshToken: string;
}
