/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */
import type { UserRecord } from './user-record';

/**
 * ユーザー一覧取得APIのレスポンス
 */
export interface UsersResponse {
    /** ユーザー情報のリスト */
    users: UserRecord[];
}
