/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */
import type { UserRecordRole } from './user-record-role';

/**
 * ユーザー情報
 */
export interface UserRecord {
    /** ユーザーID */
    id?: string;
    /** アカウント名 */
    account?: string;
    /** ユーザー名 */
    name?: string;
    /** 無効化された日時 */
    disabledAt?: string;
    /** 役割 */
    role?: UserRecordRole;
}
