/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Web System Samples
 * Webシステム開発の学習用サンプルアプリケーションです。
 * OpenAPI spec version: 0.0.0
 */
import type {
    HttpResponse as AngularHttpResponse,
    HttpContext,
    HttpEvent,
    HttpHeaders,
    HttpParams,
} from '@angular/common/http';
import { HttpClient } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { UsersResponse } from '.././model';

interface HttpClientOptions {
    headers?: HttpHeaders | Record<string, string | string[]>;
    context?: HttpContext;
    params?: HttpParams | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
    reportProgress?: boolean;
    withCredentials?: boolean;
    credentials?: RequestCredentials;
    keepalive?: boolean;
    priority?: RequestPriority;
    cache?: RequestCache;
    mode?: RequestMode;
    redirect?: RequestRedirect;
    referrer?: string;
    integrity?: string;
    transferCache?: { includeHeaders?: string[] } | boolean;
    timeout?: number;
}

@Injectable({ providedIn: 'root' })
export class MastersUsersService {
    private readonly http = inject(HttpClient);
    /**
     * 登録されているすべてのユーザー情報を取得します。
     * @summary ユーザー一覧取得API
     */
    getMastersUsers<TData = UsersResponse>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
    getMastersUsers<TData = UsersResponse>(
        options?: HttpClientOptions & { observe: 'events' },
    ): Observable<HttpEvent<TData>>;
    getMastersUsers<TData = UsersResponse>(
        options?: HttpClientOptions & { observe: 'response' },
    ): Observable<AngularHttpResponse<TData>>;
    getMastersUsers<TData = UsersResponse>(options?: HttpClientOptions & { observe?: any }): Observable<any> {
        return this.http.get<TData>(`http://localhost:56080/api/masters/users`, options);
    }
}

export type GetMastersUsersClientResult = NonNullable<UsersResponse>;
